name: Build summary

on:
  schedule:
    - cron: "*/30 * * * *"     # every 30 minutes (UTC)
  workflow_dispatch:           # allow manual runs from Actions tab

permissions:
  contents: write

concurrency:
  group: snapshot
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build snapshot
        run: |
          node --version
          node tools/build-summary.mjs

      - name: Commit snapshot
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/summary.json docs/data/summary.json
          git commit -m "snapshot: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "nothing to commit"
          git push

